version: '3'
services:
  nginx:
    build:
      context: ./docker/development
      dockerfile: nginx.docker
    volumes:
      - ./:app/
    depends_on:
      - php-fpm
    ports:
      - "8080:80"
  php-fpm:
    build:
      context: ./docker/development
      dockerfile: php-cli.docker
    volumes:
      - ./:/app